(()=>{
  let messages=[];
  const $=(s)=>document.querySelector(s);
  const escape=(v)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const formatDate=(v)=>{const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString();};
  const render=()=>{const q=($('[data-email-search]').value||'').toLowerCase().trim(),dir=$('[data-email-direction]').value;const rows=messages.filter(m=>(!dir||m.direction===dir)&&(!q||[m.from,m.to,m.subject,m.preview].join(' ').toLowerCase().includes(q)));$('[data-email-loading]').hidden=true;$('[data-email-empty]').hidden=rows.length>0;$('[data-email-table]').hidden=!rows.length;$('[data-email-count]').textContent=`${rows.length} email${rows.length===1?'':'s'}`;$('[data-email-rows]').innerHTML=rows.map(m=>`<tr><td><span class="admin-email-direction admin-email-direction--${escape(m.direction)}">${escape(m.direction)}</span></td><td class="admin-muted">${escape(formatDate(m.date))}</td><td><div><strong>From:</strong> ${escape(m.from||'—')}</div><div class="admin-muted"><strong>To:</strong> ${escape(m.to||'—')}</div></td><td><div>${escape(m.subject||'(No subject)')}</div><div class="admin-muted admin-email-preview">${escape(m.preview||'')}</div></td><td class="admin-muted">${escape(m.status||'synced')}${m.error?`<div class="field-error">${escape(m.error)}</div>`:''}</td></tr>`).join('');};
  const load=async()=>{try{const data=await AdminApi.listEmails();messages=data.messages||[];const note=$('[data-email-sync]');note.hidden=false;note.textContent=data.sync?.ok?`Google Workspace synchronized. ${data.sync.synced||0} new email(s).`:`Showing saved email. Inbox sync: ${data.sync?.error||'unavailable'}`;render();}catch(e){if(e.status===401)location.replace('../login');else{$('[data-email-loading]').innerHTML=`<p class="field-error">${escape(e.message)}</p>`;}}};
  $('[data-email-search]').addEventListener('input',render);$('[data-email-direction]').addEventListener('change',render);$('[data-email-refresh]').addEventListener('click',load);$('[data-admin-logout]').addEventListener('click',async()=>{try{await AdminApi.logout();}finally{location.href='../login';}});load();
})();
